# Site settings
title: QCQN
description:  Quantum Computing and Quantum Networks
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://sites.google.com/view/postechquantum/home"

# User settings
username: QCQN
user_description: preparing
user_title: Elecrtronic & Electrical Engineer
email: mustbestar@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
